[2024-11-22T16:24:27.002+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T16:24:27.013+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.validate_task manual__2024-11-22T16:23:21.682638+00:00 [queued]>
[2024-11-22T16:24:27.020+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_etl_pipeline.validate_task manual__2024-11-22T16:23:21.682638+00:00 [queued]>
[2024-11-22T16:24:27.020+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-22T16:24:27.043+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_task> on 2024-11-22 16:23:21.682638+00:00
[2024-11-22T16:24:27.052+0000] {logging_mixin.py:190} WARNING - /home/vboxuser/airflow/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=52468) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-22T16:24:27.060+0000] {standard_task_runner.py:72} INFO - Started process 52502 to run task
[2024-11-22T16:24:27.057+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_data_etl_pipeline', 'validate_task', 'manual__2024-11-22T16:23:21.682638+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_extraction.py', '--cfg-path', '/tmp/tmp9wuue359']
[2024-11-22T16:24:27.063+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask validate_task
[2024-11-22T16:24:27.136+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_data_etl_pipeline.validate_task manual__2024-11-22T16:23:21.682638+00:00 [running]> on host ubuntu
[2024-11-22T16:24:27.206+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team_14' AIRFLOW_CTX_DAG_ID='weather_data_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T16:23:21.682638+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-22T16:23:21.682638+00:00'
[2024-11-22T16:24:27.208+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-22T16:24:27.208+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-22T16:24:27.208+0000] {logging_mixin.py:190} INFO - Current task name:validate_task state:running start_date:2024-11-22 16:24:27.014308+00:00
[2024-11-22T16:24:27.209+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_etl_pipeline and current dag run status:running
[2024-11-22T16:24:27.209+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T16:24:27.410+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-22T16:24:27.431+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T16:24:27.440+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_data_etl_pipeline, task_id=validate_task, run_id=manual__2024-11-22T16:23:21.682638+00:00, execution_date=20241122T162321, start_date=20241122T162427, end_date=20241122T162427
[2024-11-22T16:24:27.477+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-22T16:24:27.477+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-22T16:24:27.478+0000] {logging_mixin.py:190} INFO - Dag name:weather_data_etl_pipeline queued_at:2024-11-22 16:23:21.835217+00:00
[2024-11-22T16:24:27.478+0000] {logging_mixin.py:190} INFO - Task hostname:ubuntu operator:PythonOperator
[2024-11-22T16:24:27.506+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-22T16:24:27.562+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-22T16:24:27.588+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
